/**
 * Sport Presets Configuration
 * 15 pre-configured sports with scoring systems, match formats, and display configs.
 * Used by the seed endpoint to populate the Sports Master database.
 */

const SPORT_CATEGORIES = {
  RACQUET: "Racquet",
  TEAM: "Team",
  BOARD: "Board",
  INDIVIDUAL: "Individual",
  CUSTOM: "Custom",
};

const SCORING_TYPES = {
  SETS_GAMES_POINTS: "sets-games-points",
  INNINGS_OVERS: "innings-overs",
  HALVES_GOALS: "halves-goals",
  QUARTERS_POINTS: "quarters-points",
  SINGLE_SCORE: "single-score",
  CUSTOM: "custom",
};

const sportPresets = [
  // ─── Racquet Sports ───
  {
    name: "Badminton",
    slug: "badminton",
    category: SPORT_CATEGORIES.RACQUET,
    scoringType: SCORING_TYPES.SETS_GAMES_POINTS,
    matchFormat: {
      totalSets: 3,
      gamesPerSet: null,
      pointsPerSet: 21,
      pointsPerGame: null,
      winByMargin: 2,
      maxPointsCap: 30,
      deuceEnabled: true,
      deuceMinPoints: 20,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: 21,
      serviceRules: "rally",
      halvesCount: null,
      halvesDuration: null,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "shuttlecock",
      color: "#4CAF50",
      scoreLabel: "Points",
      setLabel: "Game",
      pointLabel: "Rally",
    },
  },
  {
    name: "Table Tennis",
    slug: "table-tennis",
    category: SPORT_CATEGORIES.RACQUET,
    scoringType: SCORING_TYPES.SETS_GAMES_POINTS,
    matchFormat: {
      totalSets: 5,
      gamesPerSet: null,
      pointsPerSet: 11,
      pointsPerGame: null,
      winByMargin: 2,
      maxPointsCap: null,
      deuceEnabled: true,
      deuceMinPoints: 10,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: 11,
      serviceRules: "alternate-2",
      halvesCount: null,
      halvesDuration: null,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "table-tennis",
      color: "#FF5722",
      scoreLabel: "Points",
      setLabel: "Set",
      pointLabel: "Point",
    },
  },
  {
    name: "Tennis",
    slug: "tennis",
    category: SPORT_CATEGORIES.RACQUET,
    scoringType: SCORING_TYPES.SETS_GAMES_POINTS,
    matchFormat: {
      totalSets: 3,
      gamesPerSet: 6,
      pointsPerSet: null,
      pointsPerGame: 4,
      winByMargin: 2,
      maxPointsCap: null,
      deuceEnabled: true,
      deuceMinPoints: 3,
      tiebreakEnabled: true,
      tiebreakPoints: 7,
      decidingSetPoints: null,
      serviceRules: "alternate-game",
      halvesCount: null,
      halvesDuration: null,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "tennis",
      color: "#CDDC39",
      scoreLabel: "Points",
      setLabel: "Set",
      pointLabel: "Game",
    },
  },
  {
    name: "Pickleball",
    slug: "pickleball",
    category: SPORT_CATEGORIES.RACQUET,
    scoringType: SCORING_TYPES.SETS_GAMES_POINTS,
    matchFormat: {
      totalSets: 3,
      gamesPerSet: null,
      pointsPerSet: 11,
      pointsPerGame: null,
      winByMargin: 2,
      maxPointsCap: null,
      deuceEnabled: true,
      deuceMinPoints: 10,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: 11,
      serviceRules: "side-out",
      halvesCount: null,
      halvesDuration: null,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "pickleball",
      color: "#00BCD4",
      scoreLabel: "Points",
      setLabel: "Game",
      pointLabel: "Rally",
    },
  },

  // ─── Team Sports ───
  {
    name: "Cricket",
    slug: "cricket",
    category: SPORT_CATEGORIES.TEAM,
    scoringType: SCORING_TYPES.INNINGS_OVERS,
    matchFormat: {
      totalSets: null,
      gamesPerSet: null,
      pointsPerSet: null,
      pointsPerGame: null,
      winByMargin: null,
      maxPointsCap: null,
      deuceEnabled: false,
      deuceMinPoints: null,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: null,
      serviceRules: null,
      halvesCount: null,
      halvesDuration: null,
      quartersCount: null,
      quartersDuration: null,
      oversCount: 20,
      inningsCount: 2,
    },
    displayConfig: {
      icon: "cricket",
      color: "#8BC34A",
      scoreLabel: "Runs",
      setLabel: "Innings",
      pointLabel: "Over",
    },
  },
  {
    name: "Football",
    slug: "football",
    category: SPORT_CATEGORIES.TEAM,
    scoringType: SCORING_TYPES.HALVES_GOALS,
    matchFormat: {
      totalSets: null,
      gamesPerSet: null,
      pointsPerSet: null,
      pointsPerGame: null,
      winByMargin: null,
      maxPointsCap: null,
      deuceEnabled: false,
      deuceMinPoints: null,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: null,
      serviceRules: null,
      halvesCount: 2,
      halvesDuration: 45,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "football",
      color: "#4CAF50",
      scoreLabel: "Goals",
      setLabel: "Half",
      pointLabel: "Goal",
    },
  },
  {
    name: "Basketball",
    slug: "basketball",
    category: SPORT_CATEGORIES.TEAM,
    scoringType: SCORING_TYPES.QUARTERS_POINTS,
    matchFormat: {
      totalSets: null,
      gamesPerSet: null,
      pointsPerSet: null,
      pointsPerGame: null,
      winByMargin: null,
      maxPointsCap: null,
      deuceEnabled: false,
      deuceMinPoints: null,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: null,
      serviceRules: null,
      halvesCount: null,
      halvesDuration: null,
      quartersCount: 4,
      quartersDuration: 12,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "basketball",
      color: "#FF9800",
      scoreLabel: "Points",
      setLabel: "Quarter",
      pointLabel: "Point",
    },
  },
  {
    name: "Volleyball",
    slug: "volleyball",
    category: SPORT_CATEGORIES.TEAM,
    scoringType: SCORING_TYPES.SETS_GAMES_POINTS,
    matchFormat: {
      totalSets: 5,
      gamesPerSet: null,
      pointsPerSet: 25,
      pointsPerGame: null,
      winByMargin: 2,
      maxPointsCap: null,
      deuceEnabled: true,
      deuceMinPoints: 24,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: 15,
      serviceRules: "rotate",
      halvesCount: null,
      halvesDuration: null,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "volleyball",
      color: "#FFC107",
      scoreLabel: "Points",
      setLabel: "Set",
      pointLabel: "Rally",
    },
  },
  {
    name: "Hockey",
    slug: "hockey",
    category: SPORT_CATEGORIES.TEAM,
    scoringType: SCORING_TYPES.HALVES_GOALS,
    matchFormat: {
      totalSets: null,
      gamesPerSet: null,
      pointsPerSet: null,
      pointsPerGame: null,
      winByMargin: null,
      maxPointsCap: null,
      deuceEnabled: false,
      deuceMinPoints: null,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: null,
      serviceRules: null,
      halvesCount: 2,
      halvesDuration: 35,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "hockey",
      color: "#2196F3",
      scoreLabel: "Goals",
      setLabel: "Half",
      pointLabel: "Goal",
    },
  },
  {
    name: "Kabaddi",
    slug: "kabaddi",
    category: SPORT_CATEGORIES.TEAM,
    scoringType: SCORING_TYPES.HALVES_GOALS,
    matchFormat: {
      totalSets: null,
      gamesPerSet: null,
      pointsPerSet: null,
      pointsPerGame: null,
      winByMargin: null,
      maxPointsCap: null,
      deuceEnabled: false,
      deuceMinPoints: null,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: null,
      serviceRules: null,
      halvesCount: 2,
      halvesDuration: 20,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "kabaddi",
      color: "#E91E63",
      scoreLabel: "Points",
      setLabel: "Half",
      pointLabel: "Raid",
    },
  },

  // ─── Board / Individual Sports ───
  {
    name: "Chess",
    slug: "chess",
    category: SPORT_CATEGORIES.BOARD,
    scoringType: SCORING_TYPES.SINGLE_SCORE,
    matchFormat: {
      totalSets: null,
      gamesPerSet: null,
      pointsPerSet: null,
      pointsPerGame: null,
      winByMargin: null,
      maxPointsCap: null,
      deuceEnabled: false,
      deuceMinPoints: null,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: null,
      serviceRules: null,
      halvesCount: null,
      halvesDuration: null,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "chess",
      color: "#795548",
      scoreLabel: "Result",
      setLabel: "Game",
      pointLabel: "Move",
    },
  },
  {
    name: "Carrom",
    slug: "carrom",
    category: SPORT_CATEGORIES.BOARD,
    scoringType: SCORING_TYPES.SINGLE_SCORE,
    matchFormat: {
      totalSets: null,
      gamesPerSet: null,
      pointsPerSet: null,
      pointsPerGame: null,
      winByMargin: null,
      maxPointsCap: null,
      deuceEnabled: false,
      deuceMinPoints: null,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: null,
      serviceRules: null,
      halvesCount: null,
      halvesDuration: null,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "carrom",
      color: "#9C27B0",
      scoreLabel: "Points",
      setLabel: "Board",
      pointLabel: "Point",
    },
  },
  {
    name: "Snooker",
    slug: "snooker",
    category: SPORT_CATEGORIES.INDIVIDUAL,
    scoringType: SCORING_TYPES.SINGLE_SCORE,
    matchFormat: {
      totalSets: null,
      gamesPerSet: null,
      pointsPerSet: null,
      pointsPerGame: null,
      winByMargin: null,
      maxPointsCap: null,
      deuceEnabled: false,
      deuceMinPoints: null,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: null,
      serviceRules: null,
      halvesCount: null,
      halvesDuration: null,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "snooker",
      color: "#607D8B",
      scoreLabel: "Points",
      setLabel: "Frame",
      pointLabel: "Break",
    },
  },

  // ─── Custom / Practice Sports ───
  {
    name: "Turf Games",
    slug: "turf-games",
    category: SPORT_CATEGORIES.CUSTOM,
    scoringType: SCORING_TYPES.CUSTOM,
    matchFormat: {
      totalSets: null,
      gamesPerSet: null,
      pointsPerSet: null,
      pointsPerGame: null,
      winByMargin: null,
      maxPointsCap: null,
      deuceEnabled: false,
      deuceMinPoints: null,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: null,
      serviceRules: null,
      halvesCount: null,
      halvesDuration: null,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "turf",
      color: "#009688",
      scoreLabel: "Score",
      setLabel: "Round",
      pointLabel: "Point",
    },
  },
  {
    name: "Cricket Nets",
    slug: "cricket-nets",
    category: SPORT_CATEGORIES.CUSTOM,
    scoringType: SCORING_TYPES.CUSTOM,
    matchFormat: {
      totalSets: null,
      gamesPerSet: null,
      pointsPerSet: null,
      pointsPerGame: null,
      winByMargin: null,
      maxPointsCap: null,
      deuceEnabled: false,
      deuceMinPoints: null,
      tiebreakEnabled: false,
      tiebreakPoints: null,
      decidingSetPoints: null,
      serviceRules: null,
      halvesCount: null,
      halvesDuration: null,
      quartersCount: null,
      quartersDuration: null,
      oversCount: null,
      inningsCount: null,
    },
    displayConfig: {
      icon: "cricket-nets",
      color: "#8BC34A",
      scoreLabel: "Score",
      setLabel: "Session",
      pointLabel: "Ball",
    },
  },
];

module.exports = { sportPresets, SPORT_CATEGORIES, SCORING_TYPES };
